### ISSUE TITLE
Why do need to use lock in RPC calls?

### ISSUE THREAD

**Issue by zhazhalaila** [eliben/raft#11]
I am a newbie who just learned the go language, and when I read the following code, I was very confused.
```go
func (s *Server) Call(id int, serviceMethod string, args interface{}, reply interface{}) error {
	s.mu.Lock()
	peer := s.peerClients[id]
	s.mu.Unlock()

	// If this is called after shutdown (where client.Close is called), it will
	// return an error.
	if peer == nil {
		return fmt.Errorf("call client %d after it's closed", id)
	} else {
		return peer.Call(serviceMethod, args, reply)
	}
}
```
My understanding of locks is limited to when multiple goroutines read and write to a shared variable, the lock is needed to prevent one goroutine from reading the shared variable that other goroutines have not finished writing. In my opinion, for two RPC calls to the same node, the two RPCs are not related (in each RPC call, new parameters are generated for the call), so there is no need to lock.

**Comment by eliben** [comment]
`Call` can be called concurrently with other calls on the `Server` object. Other calls can modify `s.peerClients`, so the locking is there to protect against concurrent access.

**Comment by zhazhalaila** [comment]
I think I understand what you mean. The `DisconnectPeer` function is needed in the raft_test.go file. When a node goes offline, the server needs to acquire the lock first and then read its peerClients to ensure that has not been updated. Thanks a lot😀.
