### ISSUE TITLE
Retired old leader may send a heartbeat with a new term accepted from the new leader

### ISSUE THREAD

**Issue by lday0321** [eliben/raft#13]
Thanks for the author's articles, which is very useful for me to understand the procedure details of the raft.

I think there may be a misbehavior that the old leader may send a heartbeat with a new term accepted from the new leader: because the leader check procedure for the heartbeat sending and the real hartbeat sending with term is not atomic. 

1. when the old leader try to send a heartbeat , the check procedure is passed ( https://github.com/eliben/raft/blob/master/part3/raft.go#L576-L581 )
2. after passing the check , the old leader try to send the heartbeat, however, at this point, another candidate with higher term launch another round of vote ( this could be happened from a network partitioned follower reconnecting back), and this loader leader become a follower with the higher term
3. The heartbeat sending procedure of the old leader continues, this old leader sends a heartbeat with a higher term accepted from the new leader

I think this may be a misbehavior, the old leader should sending a heartbeat with the old term, not new(higher) term.

```
if doSend {
    heartbeat_term := 0
    cm.mu.Lock()
    if cm.state != Leader {
        cm.mu.Unlock()
        return
    }
    heartbeat_term = currentTerm
    cm.mu.Unlock()
    cm.leaderSendAEs(heartbeat_term )  // Sending heartbeat with the term of the leader term.
}
```

**Comment by eliben** [comment]
Thanks for the report.

Just wanted to leave the note that this (and your other issue) are on my TODO list but I'll need to carve out a couple of hours of focus time to page Raft context back in; this will probably happen after my upcoming vacation.

**Comment by eliben** [comment]
I looked a bit into it, and you may be right! Haven't looked deep into this code for a long while, so it took me time to load state back into my brain, so to speak. I created https://github.com/eliben/raft/pull/15 as an attempted fix - just in part 3 for now. Let me know how it looks.

FWIW I think the worst that can happen here is temporary confusion - I don't think any data will be permanently lost. The leader should have the up-to-date index log, after all.

That said, it is an easily fixable race, so why not.

**Comment by lday0321** [comment]
Thanks for your reply, the fix looks good to me.
