### ISSUE TITLE
becomeFollower may update the term from a higher one back to a low one

### ISSUE THREAD

**Issue by lday0321** [eliben/raft#14]
when the node try to become a follower, it will update its `currentTerm` to a specified term passed to `becomeFollower`

I think current implementation of `becomeFollower` may update currentTerm to low one, which may not be allowed.

There are 2 entires for a node to call `becomeFollower`: one is from the RequestVote reply, another is from the AppendEntries reply.

from AppendEntry reply, the condition for `becomeFollower(...)` is `if reply.Term > savedCurrentTerm` ( https://github.com/eliben/raft/blob/master/part3/raft.go#L620-L622 ).   This could be a misbehavior:

1. there are 5 nodes in the raft group, current node is the leader with term 1.
2. another 2 nodes (node_0, node_1) are network partitioned, node_0's vote term has been increase to 4,  node_1's vote term has been increased to 9.
3. current node send AppendEntries to all other 4 nodes, and its savedCurrentTerm is 1 right now.
4. node_1 with vote term(9) reconnected back, it sending VoteRequest with term(9),  current node becom follower by thie VoteRequest since current node's term is 1, which is less than 9 and, its currentNode has been changed to 9 in `becomeFollower`
5. node_0 with vote term(4）reconnected back, it received current node's AppendEntries and it reply this rpc with reply.Term = 4, when current node recevied this reply, it will reset its currentTerm from 9 back to 4

I think it should compare the `reply.Term` with `cm.currentTerm`, not with `savedCurrentTerm`:

```
if err := cm.server.Call(peerId, "ConsensusModule.AppendEntries", args, &reply); err == nil {
  cm.mu.Lock()
  defer cm.mu.Unlock()
  if reply.Term > cm.currentTerm {  // Not compared with savedCurrentTerm
	  cm.dlog("term out of date in heartbeat reply")
	  cm.becomeFollower(reply.Term)
	  return
  }
```

**Comment by eliben** [comment]
Thanks, this looks legit as well. I've submitted fixes.
