### ISSUE TITLE
Eternal leader

### ISSUE THREAD

**Issue by emilesalem** [eliben/raft#17]
it seems like once a leader is elected, its term is continued until it fails.

Shouldn't the term be limited in time to prevent an enduring isolated leader?

**Comment by eliben** [comment]
Is this question about the Raft protocol (as described in the Ongaro/Ousterhout paper), or specifically about my implementation? Can you describe the problematic scenario that worries you in more detail?

**Comment by emilesalem** [comment]
Thanks for taking time to answer. 
The specific problem scenario seems to be dependant on application logic, and not on your implementation or raft itself.
I was worried of problems that an isolated leader might cause, but those problems  would not concern raft's promise.
From what I understand, the isolated leader would never commit logs, and so it would in effect be counted out of the cluster with regard to data replication.
