### ISSUE TITLE
Question on the Use of lock in datastore in Part 4

### ISSUE THREAD

**Issue by zjtv** [eliben/raft#20]
Thank you for sharing this series of articles and code—it's been incredibly helpful for a beginner learning Raft! 

I have a question regarding the locking mechanism in the datastore implementation in Part 4.

If I understand correctly, based on the code and explanation, Raft log appends are linearized and thus do not experience concurrent access. Consequently, the datastore access does not seem to encounter concurrency issues (unlike in KVService, where concurrency does exist).

My question is: is the lock in datastore truly necessary in this context? If so, could you please explain the reason? Thanks in advance, and I’m eagerly looking forward to the next article in the series!

**Comment by eliben** [comment]
You're right, the mutex is not required here since only one goroutine - the _updater_ ever touches the datastore. The datastore is just an example, in reality you'd have a _real_ KV store there, of course.
I'll maybe update the blog post to not mention the mutex to avoid confusion
