### ISSUE TITLE
What if this heartbeat with empty entry ?

### ISSUE THREAD

**Issue by GEeKkk** [eliben/raft#6]
https://github.com/eliben/raft/blob/d4843212bc8a8c685729a15b94363ccaffcb2b51/part2/raft.go#L483

For example, there are 1 leader, 2 followers, 

```
[LEADER]
logs:        [x, y, z]
nextIndex[]: [3, 3, 3]
```
next heartbeat, the variable `ni = 3`, `entries := cm.log[3:] `will out of range.
Is it a bug or I miss something?

**Comment by eliben** [comment]
I suggest you run the sample with some logging (there are `dlog` calls in the code, you can add more) and try to see what happens in these scenarios. Generally range slicing will return an empty slice if the start is > length.

**Comment by GEeKkk** [comment]
> I suggest you run the sample with some logging (there are `dlog` calls in the code, you can add more) and try to see what happens in these scenarios. Generally range slicing will return an empty slice if the start is > length.

I search something, and find this. [Slice_expressions](https://golang.org/ref/spec#Slice_expressions)
It is indeed a golang feature. 
Thanks anyway.
